//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKServiceInterface.h"

@class CKDownloadQueueClient, NSArray, NSLock, NSMutableDictionary, SSDownload;

@protocol CKDownloadQueueObserver;

NS_ASSUME_NONNULL_BEGIN

@interface CKDownloadQueue : CKServiceInterface
{
    NSMutableDictionary *_downloadsByItemID;
    NSLock *_downloadsLock;
    NSMutableDictionary *_downloadQueueObservers;
    CKDownloadQueueClient *_sharedObserver;
}

+ (instancetype)sharedDownloadQueue;

@property(retain, nonatomic) CKDownloadQueueClient *sharedObserver; // @synthesize sharedObserver=_sharedObserver;
@property(retain, nonatomic) NSMutableDictionary *downloadQueueObservers; // @synthesize downloadQueueObservers=_downloadQueueObservers;

//- (void).cxx_destruct;

- (BOOL)cacheReceiptDataForDownload:(id)arg1;
- (void)checkStoreDownloadQueueForAccount:(id)arg1;
- (void)lockedApplicationTriedToLaunchAtPath:(id)arg1;
- (void)unlockApplicationsWithBundleIdentifier:(id)arg1;
- (void)lockApplicationsForBundleID:(id)arg1;
- (void)performedIconAnimationForDownloadWithIdentifier:(unsigned long long)arg1;

//- (void)fetchIconForItemIdentifier:(unsigned long long)arg1 atURL:(id)arg2 replyBlock:(CDUnknownBlockType)arg3;

- (void)removeDownloadWithItemIdentifier:(unsigned long long)arg1;
- (void)cancelDownload:(nullable SSDownload *)download promptToConfirm:(BOOL)promptToConfirm askToDelete:(BOOL)askToDelete;
- (void)resumeDownloadWithItemIdentifier:(unsigned long long)arg1;
- (void)pauseDownloadWithItemIdentifier:(unsigned long long)arg1;
- (void)addDownload:(id)arg1;
- (nullable SSDownload *)downloadForItemIdentifier:(unsigned long long)identifier;
@property(readonly, nonatomic, nullable) NSArray<SSDownload *> *downloads; // @dynamic downloads;
// Registration returns a token, not the observer object.
- (void)removeObserver:(nullable NSString *)observerUUID;
- (NSString *)addObserver:(nullable id<CKDownloadQueueObserver>)observer;
- (NSString *)addObserver:(nullable id<CKDownloadQueueObserver>)observer forDownloadTypes:(long long)downloadTypes;

// - (id)addObserverForDownloadTypes:(long long)arg1 withBlock:(CDUnknownBlockType)arg2;

- (void)connectionWasInterrupted;
- (id)initWithStoreClient:(id)arg1;

@end

NS_ASSUME_NONNULL_END
